name = "spinpossible"
globs = ["Spinpossible.+"]
defaultTargets = ["Spinpossible"]

[leanOptions]
relaxedAutoImplicit = false
# weak.linter.haveLet = 2
weak.linter.mathlibStandardSet = true
weak.linter.style.longLine = false
weak.linter.style.docString = false
weak.linter.style.setOption = false
weak.linter.style.induction = false
weak.linter.style.emptyLine = false
weak.linter.hashCommand = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.27.0-rc1"

[[require]]
name = "tryAtEachStep"
git = "https://github.com/dwrensha/tryAtEachStep"
rev = "main"

# [[require]]
# name = "LeanAideTools"
# git = "https://github.com/siddhartha-gadgil/LeanAideTools.git"
# rev = "v4.10.0"

[[lean_lib]]
name = "Spinpossible"
globs = ["Spinpossible.+"]
